export default {
  extends: ["stylelint-config-standard", "stylelint-config-tailwindcss"],
  rules: {
    "alpha-value-notation": null,
    "at-rule-empty-line-before": null,
    "color-function-notation": null,
    "color-hex-length": null,
    "comment-empty-line-before": null,
    "custom-property-pattern": null,
    "custom-property-empty-line-before": null,
    "declaration-block-single-line-max-declarations": null,
    "declaration-empty-line-before": null,
    "import-notation": null,
    "no-duplicate-selectors": null,
    "no-descending-specificity": null,
    "property-no-unknown": null,
    "property-no-vendor-prefix": null,
    "rule-empty-line-before": null,
    "selector-class-pattern": null,
    "shorthand-property-no-redundant-values": null,
    "value-keyword-case": null,
  },
};
