# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-22T09:22:00+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel


class Role(StrEnum):
    admin = 'admin'
    member = 'member'


class User(BaseModel):
    id: str
    username: str
    display_name: str
    role: Role
    created_at: AwareDatetime


class UserProfile(User):
    preferences: dict[str, Any]
    face_enrolled: bool


class Mode(StrEnum):
    text = 'text'
    voice = 'voice'


class ChatSession(BaseModel):
    id: str
    user_id: str
    title: str | None = None
    mode: Mode | None = None
    created_at: AwareDatetime
    updated_at: AwareDatetime | None = None
    ended_at: AwareDatetime | None = None


class Role1(StrEnum):
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class ChatMessage(BaseModel):
    id: str
    session_id: str
    role: Role1
    content: str
    tool_calls: list[dict[str, Any]] | None = None
    created_at: AwareDatetime


class Status(StrEnum):
    pending = 'pending'
    done = 'done'
    cancelled = 'cancelled'


class Source(StrEnum):
    manual = 'manual'
    agent = 'agent'
    rss = 'rss'
    ha = 'ha'


class Schedule(BaseModel):
    id: str
    user_id: str
    title: str
    body: str | None = None
    starts_at: AwareDatetime
    ends_at: AwareDatetime | None = None
    rrule: str | None = None
    reminder_min: int | None = None
    status: Status
    source: Source
    created_at: AwareDatetime
    updated_at: AwareDatetime


class Feed(BaseModel):
    id: str
    user_id: str
    url: AnyUrl
    title: str | None = None
    category: str | None = None
    enabled: bool
    last_fetched_at: AwareDatetime | None = None
    created_at: AwareDatetime


class FeedItem(BaseModel):
    id: str
    feed_id: str
    guid: str
    title: str
    link: str | None = None
    summary: str | None = None
    published_at: AwareDatetime | None = None
    read: bool
    starred: bool
    fetched_at: AwareDatetime


class MemoryEntry(BaseModel):
    id: str
    user_id: str
    kind: str
    content: str
    tags: list[str] | None = None
    source_msg_id: str | None = None
    weight: float
    created_at: AwareDatetime
    expires_at: AwareDatetime | None = None


class SystemStatus(BaseModel):
    ts: AwareDatetime
    cpu_pct: float
    mem_pct: float
    disk_pct: float
    gpu_count: int
    vm_count: int
    online_devices: int


class GpuProcess(BaseModel):
    pid: int
    name: str
    user: str
    gpu_mem_mb: int


class GPU(BaseModel):
    name: str
    mem_total_mb: int
    mem_used_mb: int
    util_pct: float
    temp_c: float
    processes: list[GpuProcess]


class CPUCore(BaseModel):
    index: int
    util_pct: float
    freq_mhz: float


class DiskUsage(BaseModel):
    mount: str
    total_gb: float
    used_gb: float
    util_pct: float


class Status1(StrEnum):
    running = 'running'
    paused = 'paused'
    done = 'done'
    error = 'error'


class TrainingJob(BaseModel):
    id: str
    user: str
    name: str
    status: Status1
    gpu_util_pct: float
    current_step: int
    total_steps: int | None = None
    elapsed_h: float
    eta_h: float | None = None


class SystemMetrics(BaseModel):
    ts: AwareDatetime
    cpu_cores: list[CPUCore]
    mem_total_mb: int
    mem_used_mb: int
    disks: list[DiskUsage]
    gpus: list[GPU]
    training_jobs: list[TrainingJob]


class Hypervisor(StrEnum):
    libvirt = 'libvirt'
    vbox = 'vbox'
    mock = 'mock'


class Status2(StrEnum):
    queued = 'queued'
    creating = 'creating'
    running = 'running'
    stopped = 'stopped'
    error = 'error'
    destroyed = 'destroyed'


class VM(BaseModel):
    id: str
    user_id: str
    name: str
    hypervisor: Hypervisor
    spec_cpu: int | None = None
    spec_ram_mb: int | None = None
    spec_disk_gb: int | None = None
    status: Status2
    ip: str | None = None
    notes: str | None = None
    console_path: str | None = None
    guest_agent_ok: bool
    exec_enabled: bool
    created_at: AwareDatetime


class NetworkDevice(BaseModel):
    ip: str
    mac: str
    hostname: str
    vendor: str
    online: bool
    last_seen: AwareDatetime


class Error(BaseModel):
    code: str
    message: str
    trace_id: str
